### ISSUE TITLE
No help, no documentation, no man page

### ISSUE THREAD

**Issue by nkh** [alexherbo2/bulk#3]
Bulk help displays nothing of interest

There is no documentation to be found, no man page installed.

Simply put, how is it used?!

**Comment by alexherbo2** [comment]
Just running `bulk edit` launch your editor and populate argument list (input arguments) with `*` (glob).

The syntax file is a list of `<id> <command> <output-argument>`.

Bulk comes with [some definitions][Settings] in order to be ready to use out of the box.

You can define new commands with `def <name> <command>`.  For example `def puts echo %{input} → %{output}` which defines a `puts` command that echoes input and output (edited) arguments.

When quitting you will be asked to confirm command execution.  You can accept, discard or re-edit to make changes.

[Settings]: https://github.com/alexherbo2/bulk#settings
